### ISSUE TITLE
Runner cannot load test dlls.

### ISSUE THREAD

**Issue by sylvesp** [geberit/Revit.TestRunner#11]
I am trying to use the Revit.TestRunner for some Revit testing and I am running into a problem that I hope you can help me with.

These are the steps I've done to reproduce my issue. 

1. Clone the Revit.TestRunner repository to my local machine (C:\Work\Projects\Revit.TestRunner)
2. Open C:\Work\Projects\Revit.TestRunner\src\Revit.TestRunner.sln in VS and compile the whole project for Revit 2021
3. Start Revit 2021 with No-Active-Document (so that the Revit Runner Server is Active)
   (This is done from the Windows Revit Icon and NOT from VS/ NOT debugging / VS is NOT attached to Revit)
4. Start C:\Work\Projects\Revit.TestRunner\src\bin\Client\Revit.TestRunner.App.exe
5. In the TestRunner.App.exe click the "..." and try open 
    C:\Work\Projects\Revit.TestRunner\src\bin\Revit.TestRunner.SampleTestProject2.dll

As a result I get an error message in the TestRunner.App status bar saying 
**Could not load 'C:\Work\Projects\Revit.TestRunner\src\bin\Revit.TestRunner.SampleTestProject2.dll'**

Now if I attach the VS debugger to Revit, after Revit was started at **step 3** and try to load the SampleTestProject2.dll then everything works fine - and I am able to run the tests.

Is there anything I am missing? 
Why is that the runner cannot load the test assembly when is in debug mode?
I did try to debug the issue but obviously I did fail because everything works when the debugger is attached.

I'd appreciate your help with this problem.
Please let me know if you need any extra info/log files/etc.

Peter.

**Comment by tobiasfloescher-geberit** [comment]
Hello Peter

You have done everything right.

Please check if the Revit Version is written in the TestRunner.App on the Top of the UI, beside of the Title and Version. If not, the Addin does not run correctly.
Try to start the TestRunner.App from Revit Ribbon 'Add-ins' - 'Testing - Open Runner'. 

Addin logfile path C:\Work\Projects\Revit.TestRunner\src\bin\Addin\Test.Runner.log. Please show it to me.

Tobias

**Comment by sylvesp** [comment]
Hi Tobias,

I've done the changes you've suggested above and that indeed solved the issues related to the directory from where the TestRunner.App.exe is started - so far so good.
Unfortunately this didn't solve my intermittent issues with the runner actually not loading the test dlls properly.

Finally I've got some more time and I did figure out what root of the problem is.
The simplest way to reproduce the problem is:

- Run Revit with your test framework all set up. (**Do not have VS Debugger attached to Revit**)
- On the Revit Ribbon, click the "Open Runner" button to start the Test Runner App.
- MAXIMIZE the Test Runner App (Make sure the Revit window is completely covered)
- Try to load any of your test dlls in the Test Runner App 
=> You will get the error message in the status bar of the Test Runner App saying that the test dll could not be loaded.

This is caused by the fact that while the Revit window is hidden (or no UI/API events happen in Revit), Revit will NOT send OnIdle Events to the Revit.TestRunner plugin thus causing the ExploreRequest to expire.

The OnIdle Event will be sent to the TestRunner plugin if there is any Windows UI Event affecting the Revit window, e.g. you move your mouse across the Revit Window before the ExploreRequest request expires.

Well.. that's for now. 
Although this 'easiest to reproduce' scenario may not be a 100% realistic one, still the problem with the ExploreRequests expiring because of no triggers of the Revit OnIdle status in the Revit plugin could be quite problematic, e.g. on an automated test machine.

Let me know your thoughts.

**Comment by tobiasfloescher-geberit** [comment]
Hi Peter

wow, thanks for sharing your experience. I could reproduce the issue with your description in Revit 2021. Since I mostly use Revit 2020, I did not face the problem, even with minimized Revit. The problem does not exist in Revit 2020, although the docu says it.

There would be a workaround with call of [SetRaiseWithoutDelay](https://www.revitapidocs.com/2021.1/6ead2453-9221-9044-0d93-84cc7db00b0d.htm) function, but with performance degradation, haven't tested it so far. Maybe it's time to add a possibility to activate/deactivate option for the server.

I have to think little bit more about it, and unfortunately haven't that much time at the moment. 

But I will take care of the problem and keep you updated. 
To run it on a automated test machine, we have some other issues, example how to accept the security popup without user interaction.

If you have some good inputs, let me know ;)

**Comment by tobiasfloescher-geberit** [comment]
Now I had little bit time to have a look at PokeRevit.

It looks helpful to trigger the OnIdle event. I think it will work. I have trouble to reproduce the issue. I could reproduce it, but unfortunately only once. Makes it little complicated to test this solution.
For a quick win, you can use RevitPoke and trigger it in the endless loop of StartConcurrentRoutes().

```C#
/// <summary>
/// Start endless loop of all concurrent routes.
/// </summary>
public void StartConcurrentRoutes()
{
    Task.Run( () => {
        while( true ) {
            foreach( var route in mRoutes.Where( r => r.Concurrent ) ) {
                var request = GetRouteRequest( route );

                if( request != null ) {
                    request.Execute( BasePath );
                    break;
                }
            }

            PokeRevit();
            Thread.Sleep( 200 );
        }
    } );
}

...

/// <summary>
/// Trigger Revit.OnIdle Event.
/// https://forums.autodesk.com/t5/revit-api-forum/how-to-trigger-onidle-event-or-execution-of-an-externalevent/td-p/6645286
/// </summary>
private void PokeRevit()
{
    Process revitProcess = Process.GetCurrentProcess();

    if( !revitProcess.HasExited ) {
        try {
            IntPtr mainWindowHandle = revitProcess.MainWindowHandle;
            if( mainWindowHandle.ToInt64() != 0 ) {
                PostMessage( mainWindowHandle, 0, 0, 0 );
            }
        }

        catch {
            // ignore
        }

    }
}

[DllImport( "USER32.DLL" )]
public static extern bool PostMessage( IntPtr hWnd, uint msg, uint wParam, uint lParam );
```

But I think it is only symptom control. A solution without OnIdle would probably be better. For example, with ExternalEvent and RevitTask. But this is only thinking.
The problem is the same with all non-concurrent routes. Meaning there should not be any non-concurrent routes at all.

To implement this, a change in the communication protocol is necessary. And this must be well considered (response, queueing, …)

For now, please make the change as you like in your fork or downloaded solution. unfortunately i have to deal with it at a later point in time.

Hava a nice weekend, tobias

**Comment by tobiasfloescher-geberit** [comment]
I have integrated the SetRaiseWithoutDelay version in the newest release. this keeps the OnIdle event alive.
